name: CI & Push to GitHub Container Registry

# Déclenchement du workflow
on:
  push:
    branches:
      - main

permissions:
  contents: read        # pour checkout
  packages: write       # pour publier sur GHCR
  # GITHUB_TOKEN a déjà ces permissions par défaut

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurer Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Se logger sur GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4. Build et push auth-service
      - name: Build & push auth-service
        uses: docker/build-push-action@v4
        with:
          context: ./auth-service
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/auth-service:latest

      # 5. Build et push product-service
      - name: Build & push product-service
        uses: docker/build-push-action@v4
        with:
          context: ./product-service
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/product-service:latest

      # 6. Build et push order-service
      - name: Build & push order-service
        uses: docker/build-push-action@v4
        with:
          context: ./order-service
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/order-service:latest

      # 7. Build et push api-gateway
      - name: Build & push api-gateway
        uses: docker/build-push-action@v4
        with:
          context: ./api-gateway
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/api-gateway:latest

      # 8. Build et push frontend
      - name: Build & push frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/frontend:latest

